* Info


  GIMME is an XMMS2 client for Emacs currently being developed for
  Google's Summer of Code. You can read more about it at
  http://scorciapino.com/blog/archives/49, which has some mockups, too.

  Reference
  ---------

  - Ruby bindings: http://xmms2.org/wiki/Component:Ruby_bindings
  - RDoc: http://numbers.xmms.se/~tilman/ruby-api-docs-0.7/


* TODO

  - Playlist-view:
  1. Fix the keybinding to make it look less like text
  2. Learn how broadcasts work and display the currently played track
  3. Make it prettier
  4. ???
  5. Document and refactor the code

* Known problems

** The playlist problem

   Long playlists will break playlist-view. It's kinda weird how it
   works: Emacs breaks its input into many chunks and call the
   process-filter function on each, so not only there is no guarantee
   the playlist will be in right order, but also the string will most
   certainly contain broken sexps.

   I've studied other people's code, and apparently they are using the
   same approach. I will come to this problem again soon.

* Pomodoros

  I wonder how much time I'll end up dedicating to GIMME...

  - **28/5**: 8 pomodoros working on playlist-view
  - **27/5**: 2 pomodoros trying to fix the problem with long strings. I'll come back to it later.
  - **18/5**: 4 pomodoros fixing the print system
  - **07/5**: 7 pomodoros: 1 watching ruby screencasts, 2 messing with the sexp library, 4 coding and looking for documentation
  - **06/5**: 6 pomodoros: 3 watching ruby screencasts and 3 working on code
  - **05/5**: 3 pomodoros watching Ruby screencasts on metaprogramming
  - **03/5**: 6 pomodoros: 3 wresting with output plugins and 3 wrestling with an ugly macro :(
  - **30/4**: 1 pomodoro installing xmms and its libs in this machine
  - **29/4**: 5 pomodoros building a simple ruby+emacs example

